name: FoodEffects
authors: [fernanACM, Xenophilicy]
version: 1.3.0
main: Xenophilicy\FoodEffects\FoodEffects
api: 4.0.0
Description: Enables customizable effects for interacting with and consuming items.
